export const MAKEUP = 'MAKEUP'
export const GET_IMAGE = 'GET_IMAGE'
export const REMOVE_IMAGE = 'REMOVE_IMAGE'
export const SET_IMAGE_MAKEUP = 'SET_IMAGE_MAKEUP'
export const SET_IMAGE_SHOW = 'SET_IMAGE_SHOW'
export const REQUEST = 'REQUEST'
export const ERROR = 'ERROR'